version: '3'
services:
  mall-postgres:
    image: postgres
    container_name: mall-postgres
    restart: 'always'
    environment:
      POSTGRES_USER: '${POSTGRES_USERNAME}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - '.docker-volumes/postgres/data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'